contact_links:
    - name: ðŸ“ƒ Documentation Issue
      url: https://github.com/reactjs/reactjs.org/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: ðŸ¤” Questions and Help
      url: https://stackoverflow.com/questions/tagged/react
      about: This issue tracker is not for questions. Please ask questions here.
