blank_issues_enabled: false
contact_links:
    - name: ðŸ“ƒ Documentation Issue
      url: https://github.com/reactjs/react.dev/issues/new/choose
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: ðŸ¤” Questions and Help
      url: https://reactjs.org/community/support.html
      about: This issue tracker is not for support questions. Please refer to the React community's help and discussion forums.
