# back to language cpp to try to bypass osx node failure
language: cpp
sudo: false
env:
  - export NODE_VERSION="0.10"
  - export NODE_VERSION="0.12"
  - export NODE_VERSION="4"
  - export NODE_VERSION="5"
os:
  - linux
  - osx
# pre-install to bring in the correct version of node via nvm
before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.8";
      export CXX="g++-4.8";
      export LINK="gcc-4.8";
      export LINKXX="g++-4.8";
    fi
  - gcc --version
  - g++ --version
# node 4 depends on gcc 4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
# script needed to test, because defaults don't work on osx
script:
  - npm install
  - npm run lint
