---
baseurl: /react
url: http://facebook.github.io
permalink: /blog/:year/:month/:day/:title.html
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
redcarpet:
  extensions:
  - fenced_code_blocks
pygments: true
name: React
markdown: redcarpet
react_version: 0.6.0-alpha
description: A JavaScript library for building user interfaces
relative_permalinks: true
paginate: 5
paginate_path: /blog/page:num
nav_docs_sections:
- title: Quick Start
  items:
  - id: getting-started
    title: Getting Started
  - id: tutorial
    title: Tutorial
- title: Guides
  items:
  - id: why-react
    title: Why React?
  - id: displaying-data
    title: Displaying Data
    subitems:
    - id: jsx-in-depth
      title: JSX in Depth
    - id: jsx-gotchas
      title: JSX Gotchas
  - id: interactivity-and-dynamic-uis
    title: Interactivity and Dynamic UIs
  - id: multiple-components
    title: Multiple Components
  - id: reusable-components
    title: Reusable Components
  - id: forms
    title: Forms
  - id: working-with-the-browser
    title: Working With the Browser
    subitems:
    - id: more-about-refs
      title: More About Refs
  - id: tooling-integration
    title: Tooling Integration
  - id: addons
    title: Add-ons
  - id: examples
    title: Examples
- title: Reference
  items:
  - id: top-level-api
    title: Top-Level API
  - id: component-api
    title: Component API
  - id: component-specs
    title: Component Specs and Lifecycle
  - id: tags-and-attributes
    title: Supported Tags and Attributes
  - id: events
    title: Event System
  - id: dom-differences
    title: DOM Differences
nav_tips:
- title: Tips
  items:
  - id: introduction
    title: Introduction
  - id: inline-styles
    title: Inline Styles
  - id: if-else-in-JSX
    title: If-Else in JSX
  - id: self-closing-tag
    title: Self-Closing Tag
  - id: maximum-number-of-jsx-root-nodes
    title: Maximum Number of JSX Root Nodes
  - id: style-props-value-px
    title: Shorthand for Specifying Pixel Values in style props
  - id: children-props-type
    title: Type of the Children props
  - id: controlled-input-null-value
    title: Value of null for Controlled Input
  - id: componentWillReceiveProps-not-triggered-after-mounting
    title: componentWillReceiveProps Not Triggered After Mounting
  - id: props-in-getInitialState-as-anti-pattern
    title: Props in getInitialState Is an Anti-Pattern
  - id: dom-event-listeners
    title: DOM Event Listeners in a Component
  - id: initial-ajax
    title: Load Initial Data via AJAX
  - id: false-in-jsx
    title: False in JSX
