---
markdown: redcarpet
name: React
redcarpet:
  extensions:
  - fenced_code_blocks
react_version: 0.3.2
pygments: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
baseurl: /react
permalink: /blog/:year/:month/:day/:title.html
