---
name: React
description: A JavaScript library for building user interfaces
url: https://facebook.github.io
baseurl: /react
permalink: /blog/:year/:month/:day/:title.html
paginate_path: /blog/page:num/
paginate: 5
timezone: America/Los_Angeles
highlighter: pygments
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog
- scope:
    path: tutorial
    type: pages
  values:
    layout: tutorial
    sectionid: tutorial
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
- scope:
    path: contributing
    type: pages
  values:
    sectionid: docs
- scope:
    path: community
    type: pages
  values:
    layout: community
    sectionid: community
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes
sass:
  style: :compressed
  sass_dir: _css
gems:
- jekyll-redirect-from
- jekyll-paginate
react_version: 15.6.2
react_hashes:
  dev: buVLzxzBI8Ps3svVMSUurNdb5dozNidH5Ow4H0YgZeia3t6Oeui2VLpvtAq1fwtK
  prod: nCjsa0kjNQPQdxWm12/ReVJzfBJaVubEwwDswyQDGMKYJmeWv3qShMuETfU5fisu
  addons_dev: /u97pKzBwasbC1yj8gSIq1z30o4ZTUX9j1Mv/hyAjmG41ydTNHw9JFOhwFbDgxmR
  addons_prod: /p86n4b5VTlWoA/INEHQZ+zjx9g1pJduoFmTEJ6fSzFTq1mBaXaBcWVGtZJXD68L
  dom_dev: lUxkeWjg3I3lXmxcM1gvgo0yvm2w9alc1osa4L8yWZFO6l/vg9h5hSlHPFioltrm
  dom_prod: u8x1yIGN9IjGNYbBaDMsp1D4MK3sCmMU13mcBX+bm+aMo5+gaT8HIwIj39GlXaRS
  dom_server_dev: Okj1hVX1VF+oZSkPcJQ/YcnW6bsIpeni222ylwUaMnSmdCe0zWKmMwpFMVqzy4Ws
  dom_server_prod: wiA4u+G5fEfF4xzhhVnNWeSifVyttoEIpgc3APaMKQgw5A4wHbEMihf63tk1qoyt
